import Head from "next/head";
import { useEffect } from "react";
export default function Home() {
  useEffect(() => {
    localStorage.setItem("key", "my key");
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Hello world</h2>
    </>
  );
}
